version: '3.8'

services:
  spring-app:
    image: mi-aplicacion:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev  # Ajusta según tu entorno
    networks:
      - spring-network

networks:
  spring-network:
    driver: bridge
